dist: bionic
language: java
jdk:
  - openjdk11

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: ./gradlew test
    - stage: code-quality
      name: "JaCoCo"
      script: ./gradlew jacocoTestReport
